### ISSUE TITLE
Error Installing in python3.11

### ISSUE THREAD

**Issue by alibillalhammoud** [gdsfactory/gf180#50]
`pip install gf180` fails on python version 3.11.4  
This issue only appears when installing from pypi  
I was able to install manually by cloning the repo and running `make install`

**Comment by joamatab** [comment]
Hi Ali,

yes, gf180 was using an old version of gdsfactory,

i just released a a newer version that works with gdsfactory 7 and python3.11

https://pypi.org/project/gf180/

**Comment by alibillalhammoud** [comment]
working now, thanks!

**Comment by alibillalhammoud** [comment]
working now, thanks!
